configuration:
  web:
    server:
      port: 8080
      endpoints:
        healthcheck:
          name: Healthcheck
          path: /health
          enabled: true
        error_code:
          name: Error code description location
          path: /releases/:release_version/errors/:error_code
          enabled: true
  application:
    service:
      cache:
        max_size: 1000
  adapters:
    repositories:
      properties:
        file_based:
#          properties_file_path: /home/michele/Projects/corda-open-source/tools/error-codes-server/src/main/resources/error_code.properties
          properties_file_resource_name: error_code.properties