name: Sync closed jira issues

on:
  schedule:
    - cron: '30 * * * *'

jobs:
  sync_closed:
    runs-on: ubuntu-latest
    steps:
      - name: Close
        uses: corda/jira-sync-closed-action@master
        with:
          project: CORDA
          jiraBaseUrl: https://r3-cev.atlassian.net
          jiraEmail: ${{ secrets.JIRA_USER_EMAIL }}
          jiraToken: ${{ secrets.JIRA_API_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
          owner: corda
          repository: corda
